// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.2
// source: proto/datamigration.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyValueMigrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeAddr string                 `protobuf:"bytes,1,opt,name=source_node_addr,json=sourceNodeAddr,proto3" json:"source_node_addr,omitempty"`
	DestNodeAddr   string                 `protobuf:"bytes,2,opt,name=dest_node_addr,json=destNodeAddr,proto3" json:"dest_node_addr,omitempty"`
	KvPairs        []*KVPair              `protobuf:"bytes,3,rep,name=kv_pairs,json=kvPairs,proto3" json:"kv_pairs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyValueMigrationRequest) Reset() {
	*x = KeyValueMigrationRequest{}
	mi := &file_proto_datamigration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueMigrationRequest) ProtoMessage() {}

func (x *KeyValueMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datamigration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueMigrationRequest.ProtoReflect.Descriptor instead.
func (*KeyValueMigrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_datamigration_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValueMigrationRequest) GetSourceNodeAddr() string {
	if x != nil {
		return x.SourceNodeAddr
	}
	return ""
}

func (x *KeyValueMigrationRequest) GetDestNodeAddr() string {
	if x != nil {
		return x.DestNodeAddr
	}
	return ""
}

func (x *KeyValueMigrationRequest) GetKvPairs() []*KVPair {
	if x != nil {
		return x.KvPairs
	}
	return nil
}

type KeyValueMigrationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg         string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	MigrationResults []*MigrationResult     `protobuf:"bytes,3,rep,name=migration_results,json=migrationResults,proto3" json:"migration_results,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KeyValueMigrationResponse) Reset() {
	*x = KeyValueMigrationResponse{}
	mi := &file_proto_datamigration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueMigrationResponse) ProtoMessage() {}

func (x *KeyValueMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datamigration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueMigrationResponse.ProtoReflect.Descriptor instead.
func (*KeyValueMigrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_datamigration_proto_rawDescGZIP(), []int{1}
}

func (x *KeyValueMigrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KeyValueMigrationResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *KeyValueMigrationResponse) GetMigrationResults() []*MigrationResult {
	if x != nil {
		return x.MigrationResults
	}
	return nil
}

type MigrationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationResult) Reset() {
	*x = MigrationResult{}
	mi := &file_proto_datamigration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationResult) ProtoMessage() {}

func (x *MigrationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datamigration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationResult.ProtoReflect.Descriptor instead.
func (*MigrationResult) Descriptor() ([]byte, []int) {
	return file_proto_datamigration_proto_rawDescGZIP(), []int{2}
}

func (x *MigrationResult) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MigrationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MigrationResult) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type KVPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVPair) Reset() {
	*x = KVPair{}
	mi := &file_proto_datamigration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPair) ProtoMessage() {}

func (x *KVPair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datamigration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPair.ProtoReflect.Descriptor instead.
func (*KVPair) Descriptor() ([]byte, []int) {
	return file_proto_datamigration_proto_rawDescGZIP(), []int{3}
}

func (x *KVPair) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checksum      uint32                 `protobuf:"varint,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Tombstone     uint32                 `protobuf:"varint,2,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	Timestamp     uint32                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	KeySize       uint32                 `protobuf:"varint,4,opt,name=key_size,json=keySize,proto3" json:"key_size,omitempty"`
	ValueSize     uint32                 `protobuf:"varint,5,opt,name=value_size,json=valueSize,proto3" json:"value_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_proto_datamigration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datamigration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_datamigration_proto_rawDescGZIP(), []int{4}
}

func (x *Header) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *Header) GetTombstone() uint32 {
	if x != nil {
		return x.Tombstone
	}
	return 0
}

func (x *Header) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Header) GetKeySize() uint32 {
	if x != nil {
		return x.KeySize
	}
	return 0
}

func (x *Header) GetValueSize() uint32 {
	if x != nil {
		return x.ValueSize
	}
	return 0
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	TotalSize     uint32                 `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_proto_datamigration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datamigration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_datamigration_proto_rawDescGZIP(), []int{5}
}

func (x *Record) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Record) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Record) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Record) GetTotalSize() uint32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

var File_proto_datamigration_proto protoreflect.FileDescriptor

const file_proto_datamigration_proto_rawDesc = "" +
	"\n" +
	"\x19proto/datamigration.proto\"\x8e\x01\n" +
	"\x18KeyValueMigrationRequest\x12(\n" +
	"\x10source_node_addr\x18\x01 \x01(\tR\x0esourceNodeAddr\x12$\n" +
	"\x0edest_node_addr\x18\x02 \x01(\tR\fdestNodeAddr\x12\"\n" +
	"\bkv_pairs\x18\x03 \x03(\v2\a.KVPairR\akvPairs\"\x91\x01\n" +
	"\x19KeyValueMigrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12=\n" +
	"\x11migration_results\x18\x03 \x03(\v2\x10.MigrationResultR\x10migrationResults\"Z\n" +
	"\x0fMigrationResult\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\")\n" +
	"\x06KVPair\x12\x1f\n" +
	"\x06record\x18\x01 \x01(\v2\a.RecordR\x06record\"\x9a\x01\n" +
	"\x06Header\x12\x1a\n" +
	"\bchecksum\x18\x01 \x01(\rR\bchecksum\x12\x1c\n" +
	"\ttombstone\x18\x02 \x01(\rR\ttombstone\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\rR\ttimestamp\x12\x19\n" +
	"\bkey_size\x18\x04 \x01(\rR\akeySize\x12\x1d\n" +
	"\n" +
	"value_size\x18\x05 \x01(\rR\tvalueSize\"p\n" +
	"\x06Record\x12\x1f\n" +
	"\x06header\x18\x01 \x01(\v2\a.HeaderR\x06header\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\rR\ttotalSize2e\n" +
	"\x14DataMigrationService\x12M\n" +
	"\x14MigrateKeyValuePairs\x12\x19.KeyValueMigrationRequest\x1a\x1a.KeyValueMigrationResponseB\x1eZ\x1cgithub.com/jateen67/kv/protob\x06proto3"

var (
	file_proto_datamigration_proto_rawDescOnce sync.Once
	file_proto_datamigration_proto_rawDescData []byte
)

func file_proto_datamigration_proto_rawDescGZIP() []byte {
	file_proto_datamigration_proto_rawDescOnce.Do(func() {
		file_proto_datamigration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_datamigration_proto_rawDesc), len(file_proto_datamigration_proto_rawDesc)))
	})
	return file_proto_datamigration_proto_rawDescData
}

var file_proto_datamigration_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_datamigration_proto_goTypes = []any{
	(*KeyValueMigrationRequest)(nil),  // 0: KeyValueMigrationRequest
	(*KeyValueMigrationResponse)(nil), // 1: KeyValueMigrationResponse
	(*MigrationResult)(nil),           // 2: MigrationResult
	(*KVPair)(nil),                    // 3: KVPair
	(*Header)(nil),                    // 4: Header
	(*Record)(nil),                    // 5: Record
}
var file_proto_datamigration_proto_depIdxs = []int32{
	3, // 0: KeyValueMigrationRequest.kv_pairs:type_name -> KVPair
	2, // 1: KeyValueMigrationResponse.migration_results:type_name -> MigrationResult
	5, // 2: KVPair.record:type_name -> Record
	4, // 3: Record.header:type_name -> Header
	0, // 4: DataMigrationService.MigrateKeyValuePairs:input_type -> KeyValueMigrationRequest
	1, // 5: DataMigrationService.MigrateKeyValuePairs:output_type -> KeyValueMigrationResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_datamigration_proto_init() }
func file_proto_datamigration_proto_init() {
	if File_proto_datamigration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_datamigration_proto_rawDesc), len(file_proto_datamigration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_datamigration_proto_goTypes,
		DependencyIndexes: file_proto_datamigration_proto_depIdxs,
		MessageInfos:      file_proto_datamigration_proto_msgTypes,
	}.Build()
	File_proto_datamigration_proto = out.File
	file_proto_datamigration_proto_goTypes = nil
	file_proto_datamigration_proto_depIdxs = nil
}
